name: droidcon_app
description: Flutter app for Kenya's 3rd Android Developer Conference - droidcon to be held in Nairobi from November 16-18th 2022.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  dio: ^4.0.6
  dio_cache_interceptor: ^3.3.0
  firebase_performance_dio: ^0.4.0
  firebase_analytics: ^9.3.0
  firebase_core: ^1.20.0
  firebase_crashlytics: ^2.8.6
  firebase_performance: ^0.8.2+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  freezed_annotation: ^2.1.0
  go_router: ^4.2.6
  json_serializable: ^6.3.1
  package_info_plus: ^1.4.3
  pretty_dio_logger: ^1.1.1

dev_dependencies:
  build_runner: ^2.2.0
  # flutter packages pub run build_runner watch --delete-conflicting-outputs
  change_app_package_name: ^1.1.0
  # flutter pub run change_app_package_name:main <com.new.package.name>
  flutter_launcher_icons: ^0.9.3
  # flutter pub run flutter_launcher_icons:main
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.7
  # flutter pub run flutter_native_splash:create
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  test: any

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "FFFFFF"
  image: assets/splash/splash.png


flutter:
  uses-material-design: true

  assets:
    - environments/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: assets/fonts/Schyler-Regular.ttf
  #       - asset: assets/fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: assets/fonts/TrajanPro.ttf
  #       - asset: assets/fonts/TrajanPro_Bold.ttf
  #         weight: 700
