name: droidcon_app
description: Flutter app for Kenya's 3rd Android Developer Conference - droidcon
  to be held in Nairobi from November 16-18th 2022.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.2
  community_material_icon: ^5.9.55
  dio: ^4.0.6
  dio_cache_interceptor: ^3.3.1
  drawable: ^0.1.0
  firebase_analytics: ^10.0.4
  firebase_core: ^2.1.1
  firebase_crashlytics: ^3.0.4
  firebase_performance: ^0.9.0+4
  firebase_performance_dio: ^0.4.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_form_builder: ^7.7.0
  flutter_native_splash: ^2.2.13
  flutter_riverpod: ^1.0.4
  flutter_svg: ^1.1.6
  form_builder_validators: ^8.3.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  get_time_ago: ^1.1.7
  go_router: ^5.1.3
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  http: ^0.13.5
  hydrated_riverpod: ^0.0.3
  intl: ^0.17.0
  json_serializable: ^6.5.4
  package_info: ^2.0.2
  package_info_plus: ^3.0.1
  path_provider: ^2.0.11
  pretty_dio_logger: ^1.1.1
  sizer: ^2.0.15
  social_share: ^2.2.1
  url_launcher: ^6.1.6
  video_player: ^2.4.7
  visibility_detector: ^0.3.3

dev_dependencies:
  build_runner: ^2.3.2
  # flutter packages pub run build_runner watch --delete-conflicting-outputs
  change_app_package_name: ^1.1.0
  # flutter pub run change_app_package_name:main <com.new.package.name>
  flutter_launcher_icons: ^0.10.0
  # flutter pub run flutter_launcher_icons:main
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  mockito: ^5.3.2
  # test: any

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#000000"
  image: assets/splash/splash.png
  image_dark: assets/splash/splash-dark.png
  android_gravity: bottom
  ios_content_mode: bottom
  android_12:
    image: assets/splash/splash.png
    image_dark: assets/splash/splash-dark.png
    color: "#FFFFFF"
    color_dark: "#000000"

flutter:
  uses-material-design: true
  assets:
    - environments/
    - assets/images/
    - assets/svgs/
    - assets/google_fonts/
    - assets/afrikons/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: assets/fonts/Schyler-Regular.ttf
  #       - asset: assets/fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: assets/fonts/TrajanPro.ttf
  #       - asset: assets/fonts/TrajanPro_Bold.ttf
  #         weight: 700
