name: Current Working Branch Workflow

on:
  push:
    branches:
      - '*'
      - '!dev'
      - '!main'

jobs:

  run_tests:

    runs-on: ubuntu-latest
    steps: 

    - name: Checkout files
      uses: actions/checkout@v1
    
    - uses: subosito/flutter-action@v2
      with:
        channel: stable


    - name: Flutter Clean
      run: flutter clean

    - name: Pub get
      run: flutter pub get

    - name : Run Test Coverage 
      run  : flutter test --coverage


  build_app:

    needs: [run_tests]
    runs-on: ubuntu-latest
    steps:  

    - name: Checkout files
      uses: actions/checkout@v1
    
    - uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Flutter Clean
      run: flutter clean

    - name: Pub get
      run: flutter pub get

    - name: Format code
      run: flutter format --dry-run --set-exit-if-changed .
      
    - name: Analyze static code
      run: flutter analyze

    - name: Build
      run: flutter build apk 

