name: Current Working Branch Workflow

on:
  push:
    branches:
      - '*'
      - '!dev'
      - '!main'

jobs:

  run_tests:

    runs-on: ubuntu-latest
    steps: 

    - name: Checkout files
      uses: actions/checkout@v1
    
    - name: Setup flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.0.1'   

    - name: Flutter Clean
      run: flutter clean

    - name: Pub get
      run: flutter pub get

    - name : Run Test Coverage 
      run  : flutter test --coverage


  build_app:

    needs: [run_tests]
    runs-on: ubuntu-latest
    steps:  

    - name: Checkout files
      uses: actions/checkout@v1
    
    - name: Setup flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.0.1'  

    - name: Flutter Clean
      run: flutter clean

    - name: Pub get
      run: flutter pub get


    - name: Build
      run: flutter build apk 

